<a href="https://colab.research.google.com/github/Karsuman4298/Machine_learning/blob/main/Ensemble.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.ensemble import RandomForestClassifier
from sklearn.utils import shuffle
import matplotlib.pyplot as pyplot
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.preprocessing import LabelEncoder
import torch
from sklearn.pipeline import Pipeline

In [195]:
df=pd.read_excel('Ecom.xlsx')
df

,Unnamed: 0,Unnamed: 1,CustomerID,Churn,Tenure,PreferredLoginDevice,CityTier,WarehouseToHome,PreferredPaymentMode,Gender,...,PreferedOrderCat,SatisfactionScore,MaritalStatus,NumberOfAddress,Complain,OrderAmountHikeFromlastYear,CouponUsed,OrderCount,DaySinceLastOrder,CashbackAmount
0,NaN,NaN,50001,1,4.0,Mobile Phone,3,6.0,Debit Card,Female,...,Laptop & Accessory,2,Single,9,1,11.0,1.0,1.0,5.0,159.93
1,NaN,NaN,50002,1,NaN,Phone,1,8.0,UPI,Male,...,Mobile,3,Single,7,1,15.0,0.0,1.0,0.0,120.90
2,NaN,NaN,50003,1,NaN,Phone,1,30.0,Debit Card,Male,...,Mobile,3,Single,6,1,14.0,0.0,1.0,3.0,120.28
3,NaN,NaN,50004,1,0.0,Phone,3,15.0,Debit Card,Male,...,Laptop & Accessory,5,Single,8,0,23.0,0.0,1.0,3.0,134.07
4,NaN,NaN,50005,1,0.0,Phone,1,12.0,CC,Male,...,Mobile,5,Single,3,0,11.0,1.0,1.0,3.0,129.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5625,NaN,NaN,55626,0,10.0,Computer,1,30.0,Credit Card,Male,...,Laptop & Accessory,1,Married,6,0,18.0,1.0,2.0,4.0,150.71
5626,NaN,NaN,55627,0,13.0,Mobile Phone,1,13.0,Credit Card,Male,...,Fashion,5,Married,6,0,16.0,1.0,2.0,NaN,224.91
5627,NaN,NaN,55628,0,1.0,Mobile Phone,1,11.0,Debit Card,Male,...,Laptop & Accessory,4,Married,3,1,21.0,1.0,2.0,4.0,186.42
5628,NaN,NaN,55629,0,23.0,Computer,3,9.0,Credit Card,Male,...,Laptop & Accessory,4,Married,4,0,15.0,2.0,2.0,9.0,178.90
5629,NaN,NaN,55630,0,8.0,Mobile Phone,1,15.0,Credit Card,Male,...,Laptop & Accessory,3,Married,4,0,13.0,2.0,2.0,3.0,169.04

In [196]:
df.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'CustomerID', 'Churn', 'Tenure',
       'PreferredLoginDevice', 'CityTier', 'WarehouseToHome',
       'PreferredPaymentMode', 'Gender', 'HourSpendOnApp',
       'NumberOfDeviceRegistered', 'PreferedOrderCat', 'SatisfactionScore',
       'MaritalStatus', 'NumberOfAddress', 'Complain',
       'OrderAmountHikeFromlastYear', 'CouponUsed', 'OrderCount',
       'DaySinceLastOrder', 'CashbackAmount'],
      dtype='object')

In [198]:
df.head(5)

,Unnamed: 0,Unnamed: 1,CustomerID,Churn,Tenure,PreferredLoginDevice,CityTier,WarehouseToHome,PreferredPaymentMode,Gender,...,PreferedOrderCat,SatisfactionScore,MaritalStatus,NumberOfAddress,Complain,OrderAmountHikeFromlastYear,CouponUsed,OrderCount,DaySinceLastOrder,CashbackAmount
0,NaN,NaN,50001,1,4.0,Mobile Phone,3,6.0,Debit Card,Female,...,Laptop & Accessory,2,Single,9,1,11.0,1.0,1.0,5.0,159.93
1,NaN,NaN,50002,1,NaN,Phone,1,8.0,UPI,Male,...,Mobile,3,Single,7,1,15.0,0.0,1.0,0.0,120.90
2,NaN,NaN,50003,1,NaN,Phone,1,30.0,Debit Card,Male,...,Mobile,3,Single,6,1,14.0,0.0,1.0,3.0,120.28
3,NaN,NaN,50004,1,0.0,Phone,3,15.0,Debit Card,Male,...,Laptop & Accessory,5,Single,8,0,23.0,0.0,1.0,3.0,134.07
4,NaN,NaN,50005,1,0.0,Phone,1,12.0,CC,Male,...,Mobile,5,Single,3,0,11.0,1.0,1.0,3.0,129.60

In [199]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 23 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Unnamed: 1_Data                         21 non-null     bool
 1   Unnamed: 1_E Comm                       21 non-null     bool
 2   Unnamed: 2_CashbackAmount               21 non-null     bool
 3   Unnamed: 2_Churn                        21 non-null     bool
 4   Unnamed: 2_CityTier                     21 non-null     bool
 5   Unnamed: 2_Complain                     21 non-null     bool
 6   Unnamed: 2_CouponUsed                   21 non-null     bool
 7   Unnamed: 2_CustomerID                   21 non-null     bool
 8   Unnamed: 2_DaySinceLastOrder            21 non-null     bool
 9   Unnamed: 2_Gender                       21 non-null     bool
 10  Unnamed: 2_HourSpendOnApp               21 non-null     bool
 11  Unnamed: 2_MaritalStatus                21 non-null     bool
 12  Unnamed: 2_NumberOfAddress              21 non-null     bool
 13  Unnamed: 2_NumberOfDeviceRegistered     21 non-null     bool
 14  Unnamed: 2_OrderAmountHikeFromlastYear  21 non-null     bool
 15  Unnamed: 2_OrderCount                   21 non-null     bool
 16  Unnamed: 2_PreferedOrderCat             21 non-null     bool
 17  Unnamed: 2_PreferredLoginDevice         21 non-null     bool
 18  Unnamed: 2_PreferredPaymentMode         21 non-null     bool
 19  Unnamed: 2_SatisfactionScore            21 non-null     bool
 20  Unnamed: 2_Tenure                       21 non-null     bool
 21  Unnamed: 2_Variable                     21 non-null     bool
 22  Unnamed: 2_WarehouseToHome              21 non-null     bool
dtypes: bool(23)
memory usage: 615.0 bytes

In [200]:
df.isnull().sum()

Unnamed: 0                     5630
Unnamed: 1                     5630
CustomerID                        0
Churn                             0
Tenure                          264
PreferredLoginDevice              0
CityTier                          0
WarehouseToHome                 251
PreferredPaymentMode              0
Gender                            0
HourSpendOnApp                  255
NumberOfDeviceRegistered          0
PreferedOrderCat                  0
SatisfactionScore                 0
MaritalStatus                     0
NumberOfAddress                   0
Complain                          0
OrderAmountHikeFromlastYear     265
CouponUsed                      256
OrderCount                      258
DaySinceLastOrder               307
CashbackAmount                    0
dtype: int64

In [201]:
df.backfill()

/tmp/ipykernel_4044/2806377195.py:1: FutureWarning: DataFrame.backfill/Series.backfill is deprecated. Use DataFrame.bfill/Series.bfill instead
  df.backfill()

,Unnamed: 0,Unnamed: 1,CustomerID,Churn,Tenure,PreferredLoginDevice,CityTier,WarehouseToHome,PreferredPaymentMode,Gender,...,PreferedOrderCat,SatisfactionScore,MaritalStatus,NumberOfAddress,Complain,OrderAmountHikeFromlastYear,CouponUsed,OrderCount,DaySinceLastOrder,CashbackAmount
0,NaN,NaN,50001,1,4.0,Mobile Phone,3,6.0,Debit Card,Female,...,Laptop & Accessory,2,Single,9,1,11.0,1.0,1.0,5.0,159.93
1,NaN,NaN,50002,1,0.0,Phone,1,8.0,UPI,Male,...,Mobile,3,Single,7,1,15.0,0.0,1.0,0.0,120.90
2,NaN,NaN,50003,1,0.0,Phone,1,30.0,Debit Card,Male,...,Mobile,3,Single,6,1,14.0,0.0,1.0,3.0,120.28
3,NaN,NaN,50004,1,0.0,Phone,3,15.0,Debit Card,Male,...,Laptop & Accessory,5,Single,8,0,23.0,0.0,1.0,3.0,134.07
4,NaN,NaN,50005,1,0.0,Phone,1,12.0,CC,Male,...,Mobile,5,Single,3,0,11.0,1.0,1.0,3.0,129.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5625,NaN,NaN,55626,0,10.0,Computer,1,30.0,Credit Card,Male,...,Laptop & Accessory,1,Married,6,0,18.0,1.0,2.0,4.0,150.71
5626,NaN,NaN,55627,0,13.0,Mobile Phone,1,13.0,Credit Card,Male,...,Fashion,5,Married,6,0,16.0,1.0,2.0,4.0,224.91
5627,NaN,NaN,55628,0,1.0,Mobile Phone,1,11.0,Debit Card,Male,...,Laptop & Accessory,4,Married,3,1,21.0,1.0,2.0,4.0,186.42
5628,NaN,NaN,55629,0,23.0,Computer,3,9.0,Credit Card,Male,...,Laptop & Accessory,4,Married,4,0,15.0,2.0,2.0,9.0,178.90
5629,NaN,NaN,55630,0,8.0,Mobile Phone,1,15.0,Credit Card,Male,...,Laptop & Accessory,3,Married,4,0,13.0,2.0,2.0,3.0,169.04

In [202]:
df.isnull().isna().sum()

Unnamed: 0                     0
Unnamed: 1                     0
CustomerID                     0
Churn                          0
Tenure                         0
PreferredLoginDevice           0
CityTier                       0
WarehouseToHome                0
PreferredPaymentMode           0
Gender                         0
HourSpendOnApp                 0
NumberOfDeviceRegistered       0
PreferedOrderCat               0
SatisfactionScore              0
MaritalStatus                  0
NumberOfAddress                0
Complain                       0
OrderAmountHikeFromlastYear    0
CouponUsed                     0
OrderCount                     0
DaySinceLastOrder              0
CashbackAmount                 0
dtype: int64

In [ ]:
y.shape

(21,)

In [ ]:
!pip install scikit-optimize

Requirement already satisfied: scikit-optimize in /usr/local/lib/python3.12/dist-packages (0.10.2)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.12/dist-packages (from scikit-optimize) (1.5.3)
Requirement already satisfied: pyaml>=16.9 in /usr/local/lib/python3.12/dist-packages (from scikit-optimize) (26.2.1)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.12/dist-packages (from scikit-optimize) (2.0.2)
Requirement already satisfied: scipy>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-optimize) (1.16.3)
Requirement already satisfied: scikit-learn>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from scikit-optimize) (1.6.1)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.12/dist-packages (from scikit-optimize) (26.0)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from pyaml>=16.9->scikit-optimize) (6.0.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.0.0->scikit-optimize) (3.6.0)

In [203]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [204]:
pipeline = Pipeline([
    ('rf', RandomForestClassifier(random_state=0, n_jobs=-1))
])

search_space = {
    'rf__n_estimators': (100, 500),
    'rf__max_depth': (5, 45),
    'rf__min_samples_split': (2, 20),
    'rf__min_samples_leaf': (1, 10),
    'rf__max_features': ['sqrt', 'log2', None]
}

In [205]:
y_train

array([ 3, 17, 19,  6,  7, 11, 12,  5,  4, 13,  2, 16,  0, 15,  8, 18])

In [ ]:
y_test

array([10, 17,  0, 19,  8])

In [206]:
import xgboost as xgb

In [207]:
y

array([ 5, 20,  2, 15, 11,  3,  6, 13,  7,  9, 18, 12, 14,  8, 16,  0, 10,
       17, 19,  4,  1])

In [215]:
import pandas as pd
import numpy as np

X_train = X
y_train = y_encoded
X_test = pd.DataFrame() # Create an empty DataFrame for X_test
y_test = np.array([])  # Create an empty NumPy array for y_test

In [209]:
from collections import Counter
print("Train:", Counter(y_train))
print("Test:", Counter(y_test))

Train: Counter({np.int64(3): 1, np.int64(12): 1, np.int64(15): 1, np.int64(19): 1, np.int64(10): 1, np.int64(8): 1, np.int64(2): 1, np.int64(9): 1, np.int64(1): 1, np.int64(11): 1, np.int64(14): 1, np.int64(13): 1, np.int64(18): 1, np.int64(16): 1, np.int64(4): 1, np.int64(6): 1})
Test: Counter({np.int64(5): 1, np.int64(17): 1, np.int64(0): 1, np.int64(20): 1, np.int64(7): 1})

In [210]:
X_train = pd.get_dummies(X_train)
X_test = pd.get_dummies(X_test)

X_train, X_test = X_train.align(X_test, join="left", axis=1, fill_value=0)

In [216]:
from xgboost import XGBClassifier
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y_encoded = le.fit_transform(y)

y_train_encoded = le.transform(y_train)
y_test_encoded = le.transform(y_test)

model = XGBClassifier(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    random_state=42,
    num_class=len(le.classes_)
)

model.fit(X_train, y_train_encoded)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.05, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=300,
              n_jobs=None, num_class=21, ...)

In [220]:
classification_report=classification_report(y_test,y_pred)

NameError: name 'y_pred' is not defined